import { createSlice, PayloadAction } from '@reduxjs/toolkit';

type CarData = {
  name: string;
  color: string;
  id?: number;
};
type GarageState = {
  list: CarData[];
};
const initialState: GarageState = {
  list: [
    {
      name: 'Tesla',
      color: '#e6e6fa',
      id: 1
    },
    {
      name: 'BMW',
      color: '#fede00',
      id: 2
    },
    {
      name: 'Mersedes',
      color: '#6c779f',
      id: 3
    },
    {
      name: 'Ford',
      color: '#ef3c40',
      id: 4
    }
  ]
};
export const garageSlice = createSlice({
  name: 'garage',
  initialState,
  // The `reducers` field lets us define reducers and generate associated actions
  reducers: {
    addCarReduser: (state, action: PayloadAction<CarData>) => {
      state.list.push(action.payload);
    }
  }
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
});

console.log(initialState);
export const { addCarReduser } = garageSlice.actions;

export default garageSlice.reducer;
